const elementsData = [
    // --- Period 1 ---
    { name: "Hydrogen", symbol: "H", atomicNumber: 1, molarMass: 1.008, group: "nonmetal", grid: { row: 1, col: 1 } },
    { name: "Helium", symbol: "He", atomicNumber: 2, molarMass: 4.003, group: "noble-gas", grid: { row: 1, col: 18 } },
    
    // --- Period 2 ---
    { name: "Lithium", symbol: "Li", atomicNumber: 3, molarMass: 6.94, group: "alkali-metal", grid: { row: 2, col: 1 } },
    { name: "Beryllium", symbol: "Be", atomicNumber: 4, molarMass: 9.012, group: "alkaline-earth-metal", grid: { row: 2, col: 2 } },
    { name: "Boron", symbol: "B", atomicNumber: 5, molarMass: 10.81, group: "metalloid", grid: { row: 2, col: 13 } },
    { name: "Carbon", symbol: "C", atomicNumber: 6, molarMass: 12.011, group: "nonmetal", grid: { row: 2, col: 14 } },
    { name: "Nitrogen", symbol: "N", atomicNumber: 7, molarMass: 14.007, group: "nonmetal", grid: { row: 2, col: 15 } },
    { name: "Oxygen", symbol: "O", atomicNumber: 8, molarMass: 15.999, group: "nonmetal", grid: { row: 2, col: 16 } },
    { name: "Fluorine", symbol: "F", atomicNumber: 9, molarMass: 18.998, group: "halogen", grid: { row: 2, col: 17 } },
    { name: "Neon", symbol: "Ne", atomicNumber: 10, molarMass: 20.180, group: "noble-gas", grid: { row: 2, col: 18 } },
    
    // --- Period 3 ---
    { name: "Sodium", symbol: "Na", atomicNumber: 11, molarMass: 22.990, group: "alkali-metal", grid: { row: 3, col: 1 } },
    { name: "Magnesium", symbol: "Mg", atomicNumber: 12, molarMass: 24.305, group: "alkaline-earth-metal", grid: { row: 3, col: 2 } },
    { name: "Aluminum", symbol: "Al", atomicNumber: 13, molarMass: 26.982, group: "post-transition-metal", grid: { row: 3, col: 13 } },
    { name: "Silicon", symbol: "Si", atomicNumber: 14, molarMass: 28.085, group: "metalloid", grid: { row: 3, col: 14 } },
    { name: "Phosphorus", symbol: "P", atomicNumber: 15, molarMass: 30.974, group: "nonmetal", grid: { row: 3, col: 15 } },
    { name: "Sulfur", symbol: "S", atomicNumber: 16, molarMass: 32.06, group: "nonmetal", grid: { row: 3, col: 16 } },
    { name: "Chlorine", symbol: "Cl", atomicNumber: 17, molarMass: 35.45, group: "halogen", grid: { row: 3, col: 17 } },
    { name: "Argon", symbol: "Ar", atomicNumber: 18, molarMass: 39.948, group: "noble-gas", grid: { row: 3, col: 18 } },
    
    // --- Period 4 ---
    { name: "Potassium", symbol: "K", atomicNumber: 19, molarMass: 39.098, group: "alkali-metal", grid: { row: 4, col: 1 } },
    { name: "Calcium", symbol: "Ca", atomicNumber: 20, molarMass: 40.078, group: "alkaline-earth-metal", grid: { row: 4, col: 2 } },
    { name: "Scandium", symbol: "Sc", atomicNumber: 21, molarMass: 44.956, group: "transition-metal", grid: { row: 4, col: 3 } },
    { name: "Titanium", symbol: "Ti", atomicNumber: 22, molarMass: 47.867, group: "transition-metal", grid: { row: 4, col: 4 } },
    { name: "Vanadium", symbol: "V", atomicNumber: 23, molarMass: 50.942, group: "transition-metal", grid: { row: 4, col: 5 } },
    { name: "Chromium", symbol: "Cr", atomicNumber: 24, molarMass: 51.996, group: "transition-metal", grid: { row: 4, col: 6 } },
    { name: "Manganese", symbol: "Mn", atomicNumber: 25, molarMass: 54.938, group: "transition-metal", grid: { row: 4, col: 7 } },
    { name: "Iron", symbol: "Fe", atomicNumber: 26, molarMass: 55.845, group: "transition-metal", grid: { row: 4, col: 8 } },
    { name: "Cobalt", symbol: "Co", atomicNumber: 27, molarMass: 58.933, group: "transition-metal", grid: { row: 4, col: 9 } },
    { name: "Nickel", symbol: "Ni", atomicNumber: 28, molarMass: 58.693, group: "transition-metal", grid: { row: 4, col: 10 } },
    { name: "Copper", symbol: "Cu", atomicNumber: 29, molarMass: 63.546, group: "transition-metal", grid: { row: 4, col: 11 } },
    { name: "Zinc", symbol: "Zn", atomicNumber: 30, molarMass: 65.38, group: "transition-metal", grid: { row: 4, col: 12 } },
    { name: "Gallium", symbol: "Ga", atomicNumber: 31, molarMass: 69.723, group: "post-transition-metal", grid: { row: 4, col: 13 } },
    { name: "Germanium", symbol: "Ge", atomicNumber: 32, molarMass: 72.63, group: "metalloid", grid: { row: 4, col: 14 } },
    { name: "Arsenic", symbol: "As", atomicNumber: 33, molarMass: 74.922, group: "metalloid", grid: { row: 4, col: 15 } },
    { name: "Selenium", symbol: "Se", atomicNumber: 34, molarMass: 78.971, group: "nonmetal", grid: { row: 4, col: 16 } },
    { name: "Bromine", symbol: "Br", atomicNumber: 35, molarMass: 79.904, group: "halogen", grid: { row: 4, col: 17 } },
    { name: "Krypton", symbol: "Kr", atomicNumber: 36, molarMass: 83.798, group: "noble-gas", grid: { row: 4, col: 18 } },
    
    // --- Period 5 ---
    { name: "Rubidium", symbol: "Rb", atomicNumber: 37, molarMass: 85.468, group: "alkali-metal", grid: { row: 5, col: 1 } },
    { name: "Strontium", symbol: "Sr", atomicNumber: 38, molarMass: 87.62, group: "alkaline-earth-metal", grid: { row: 5, col: 2 } },
    { name: "Yttrium", symbol: "Y", atomicNumber: 39, molarMass: 88.906, group: "transition-metal", grid: { row: 5, col: 3 } },
    { name: "Zirconium", symbol: "Zr", atomicNumber: 40, molarMass: 91.224, group: "transition-metal", grid: { row: 5, col: 4 } },
    { name: "Niobium", symbol: "Nb", atomicNumber: 41, molarMass: 92.906, group: "transition-metal", grid: { row: 5, col: 5 } },
    { name: "Molybdenum", symbol: "Mo", atomicNumber: 42, molarMass: 95.96, group: "transition-metal", grid: { row: 5, col: 6 } },
    { name: "Technetium", symbol: "Tc", atomicNumber: 43, molarMass: 98, group: "transition-metal", grid: { row: 5, col: 7 } },
    { name: "Ruthenium", symbol: "Ru", atomicNumber: 44, molarMass: 101.07, group: "transition-metal", grid: { row: 5, col: 8 } },
    { name: "Rhodium", symbol: "Rh", atomicNumber: 45, molarMass: 102.91, group: "transition-metal", grid: { row: 5, col: 9 } },
    { name: "Palladium", symbol: "Pd", atomicNumber: 46, molarMass: 106.42, group: "transition-metal", grid: { row: 5, col: 10 } },
    { name: "Silver", symbol: "Ag", atomicNumber: 47, molarMass: 107.87, group: "transition-metal", grid: { row: 5, col: 11 } },
    { name: "Cadmium", symbol: "Cd", atomicNumber: 48, molarMass: 112.41, group: "transition-metal", grid: { row: 5, col: 12 } },
    { name: "Indium", symbol: "In", atomicNumber: 49, molarMass: 114.82, group: "post-transition-metal", grid: { row: 5, col: 13 } },
    { name: "Tin", symbol: "Sn", atomicNumber: 50, molarMass: 118.71, group: "post-transition-metal", grid: { row: 5, col: 14 } },
    { name: "Antimony", symbol: "Sb", atomicNumber: 51, molarMass: 121.76, group: "metalloid", grid: { row: 5, col: 15 } },
    { name: "Tellurium", symbol: "Te", atomicNumber: 52, molarMass: 127.60, group: "metalloid", grid: { row: 5, col: 16 } },
    { name: "Iodine", symbol: "I", atomicNumber: 53, molarMass: 126.90, group: "halogen", grid: { row: 5, col: 17 } },
    { name: "Xenon", symbol: "Xe", atomicNumber: 54, molarMass: 131.29, group: "noble-gas", grid: { row: 5, col: 18 } },
    
    // --- Period 6 ---
    { name: "Cesium", symbol: "Cs", atomicNumber: 55, molarMass: 132.91, group: "alkali-metal", grid: { row: 6, col: 1 } },
    { name: "Barium", symbol: "Ba", atomicNumber: 56, molarMass: 137.33, group: "alkaline-earth-metal", grid: { row: 6, col: 2 } },
    // **Lanthanides (57-71) Placeholder: grid.col: 3, row: 6. Actual elements are typically placed in row 8.**
    { name: "Lanthanum Series", symbol: "57-71", atomicNumber: 57, molarMass: 0, group: "lanthanide-placeholder", grid: { row: 6, col: 3 } }, 
    { name: "Hafnium", symbol: "Hf", atomicNumber: 72, molarMass: 178.49, group: "transition-metal", grid: { row: 6, col: 4 } },
    { name: "Tantalum", symbol: "Ta", atomicNumber: 73, molarMass: 180.95, group: "transition-metal", grid: { row: 6, col: 5 } },
    { name: "Tungsten", symbol: "W", atomicNumber: 74, molarMass: 183.84, group: "transition-metal", grid: { row: 6, col: 6 } },
    { name: "Rhenium", symbol: "Re", atomicNumber: 75, molarMass: 186.21, group: "transition-metal", grid: { row: 6, col: 7 } },
    { name: "Osmium", symbol: "Os", atomicNumber: 76, molarMass: 190.23, group: "transition-metal", grid: { row: 6, col: 8 } },
    { name: "Iridium", symbol: "Ir", atomicNumber: 77, molarMass: 192.22, group: "transition-metal", grid: { row: 6, col: 9 } },
    { name: "Platinum", symbol: "Pt", atomicNumber: 78, molarMass: 195.08, group: "transition-metal", grid: { row: 6, col: 10 } },
    { name: "Gold", symbol: "Au", atomicNumber: 79, molarMass: 196.97, group: "transition-metal", grid: { row: 6, col: 11 } },
    { name: "Mercury", symbol: "Hg", atomicNumber: 80, molarMass: 200.59, group: "transition-metal", grid: { row: 6, col: 12 } },
    { name: "Thallium", symbol: "Tl", atomicNumber: 81, molarMass: 204.38, group: "post-transition-metal", grid: { row: 6, col: 13 } },
    { name: "Lead", symbol: "Pb", atomicNumber: 82, molarMass: 207.2, group: "post-transition-metal", grid: { row: 6, col: 14 } },
    { name: "Bismuth", symbol: "Bi", atomicNumber: 83, molarMass: 208.98, group: "post-transition-metal", grid: { row: 6, col: 15 } },
    { name: "Polonium", symbol: "Po", atomicNumber: 84, molarMass: 209, group: "metalloid", grid: { row: 6, col: 16 } },
    { name: "Astatine", symbol: "At", atomicNumber: 85, molarMass: 210, group: "halogen", grid: { row: 6, col: 17 } },
    { name: "Radon", symbol: "Rn", atomicNumber: 86, molarMass: 222, group: "noble-gas", grid: { row: 6, col: 18 } },
    
    // --- Period 7 ---
    { name: "Francium", symbol: "Fr", atomicNumber: 87, molarMass: 223, group: "alkali-metal", grid: { row: 7, col: 1 } },
    { name: "Radium", symbol: "Ra", atomicNumber: 88, molarMass: 226, group: "alkaline-earth-metal", grid: { row: 7, col: 2 } },
    // **Actinides (89-103) Placeholder: grid.col: 3, row: 7. Actual elements are typically placed in row 9.**
    { name: "Actinium Series", symbol: "89-103", atomicNumber: 89, molarMass: 0, group: "actinide-placeholder", grid: { row: 7, col: 3 } },
    { name: "Rutherfordium", symbol: "Rf", atomicNumber: 104, molarMass: 267, group: "transition-metal", grid: { row: 7, col: 4 } },
    { name: "Dubnium", symbol: "Db", atomicNumber: 105, molarMass: 268, group: "transition-metal", grid: { row: 7, col: 5 } },
    { name: "Seaborgium", symbol: "Sg", atomicNumber: 106, molarMass: 271, group: "transition-metal", grid: { row: 7, col: 6 } },
    { name: "Bohrium", symbol: "Bh", atomicNumber: 107, molarMass: 272, group: "transition-metal", grid: { row: 7, col: 7 } },
    { name: "Hassium", symbol: "Hs", atomicNumber: 108, molarMass: 270, group: "transition-metal", grid: { row: 7, col: 8 } },
    { name: "Meitnerium", symbol: "Mt", atomicNumber: 109, molarMass: 276, group: "transition-metal", grid: { row: 7, col: 9 } },
    { name: "Darmstadtium", symbol: "Ds", atomicNumber: 110, molarMass: 281, group: "transition-metal", grid: { row: 7, col: 10 } },
    { name: "Roentgenium", symbol: "Rg", atomicNumber: 111, molarMass: 280, group: "transition-metal", grid: { row: 7, col: 11 } },
    { name: "Copernicium", symbol: "Cn", atomicNumber: 112, molarMass: 285, group: "transition-metal", grid: { row: 7, col: 12 } },
    { name: "Nihonium", symbol: "Nh", atomicNumber: 113, molarMass: 286, group: "unknown", grid: { row: 7, col: 13 } },
    { name: "Flerovium", symbol: "Fl", atomicNumber: 114, molarMass: 289, group: "unknown", grid: { row: 7, col: 14 } },
    { name: "Moscovium", symbol: "Mc", atomicNumber: 115, molarMass: 290, group: "unknown", grid: { row: 7, col: 15 } },
    { name: "Livermorium", symbol: "Lv", atomicNumber: 116, molarMass: 293, group: "unknown", grid: { row: 7, col: 16 } },
    { name: "Tennessine", symbol: "Ts", atomicNumber: 117, molarMass: 294, group: "unknown", grid: { row: 7, col: 17 } },
    { name: "Oganesson", symbol: "Og", atomicNumber: 118, molarMass: 294, group: "unknown", grid: { row: 7, col: 18 } },

    // --- Lanthanides (F-Block - Displayed in separate rows 8/9 for modern tables) ---
    { name: "Lanthanum", symbol: "La", atomicNumber: 57, molarMass: 138.91, group: "lanthanide", grid: { row: 8, col: 4 } },
    { name: "Cerium", symbol: "Ce", atomicNumber: 58, molarMass: 140.12, group: "lanthanide", grid: { row: 8, col: 5 } },
    { name: "Praseodymium", symbol: "Pr", atomicNumber: 59, molarMass: 140.91, group: "lanthanide", grid: { row: 8, col: 6 } },
    { name: "Neodymium", symbol: "Nd", atomicNumber: 60, molarMass: 144.24, group: "lanthanide", grid: { row: 8, col: 7 } },
    { name: "Promethium", symbol: "Pm", atomicNumber: 61, molarMass: 145, group: "lanthanide", grid: { row: 8, col: 8 } },
    { name: "Samarium", symbol: "Sm", atomicNumber: 62, molarMass: 150.36, group: "lanthanide", grid: { row: 8, col: 9 } },
    { name: "Europium", symbol: "Eu", atomicNumber: 63, molarMass: 151.96, group: "lanthanide", grid: { row: 8, col: 10 } },
    { name: "Gadolinium", symbol: "Gd", atomicNumber: 64, molarMass: 157.25, group: "lanthanide", grid: { row: 8, col: 11 } },
    { name: "Terbium", symbol: "Tb", atomicNumber: 65, molarMass: 158.93, group: "lanthanide", grid: { row: 8, col: 12 } },
    { name: "Dysprosium", symbol: "Dy", atomicNumber: 66, molarMass: 162.50, group: "lanthanide", grid: { row: 8, col: 13 } },
    { name: "Holmium", symbol: "Ho", atomicNumber: 67, molarMass: 164.93, group: "lanthanide", grid: { row: 8, col: 14 } },
    { name: "Erbium", symbol: "Er", atomicNumber: 68, molarMass: 167.26, group: "lanthanide", grid: { row: 8, col: 15 } },
    { name: "Thulium", symbol: "Tm", atomicNumber: 69, molarMass: 168.93, group: "lanthanide", grid: { row: 8, col: 16 } },
    { name: "Ytterbium", symbol: "Yb", atomicNumber: 70, molarMass: 173.05, group: "lanthanide", grid: { row: 8, col: 17 } },
    { name: "Lutetium", symbol: "Lu", atomicNumber: 71, molarMass: 174.97, group: "lanthanide", grid: { row: 8, col: 18 } },
    
    // --- Actinides (F-Block - Displayed in separate rows 8/9 for modern tables) ---
    { name: "Actinium", symbol: "Ac", atomicNumber: 89, molarMass: 227, group: "actinide", grid: { row: 9, col: 4 } },
    { name: "Thorium", symbol: "Th", atomicNumber: 90, molarMass: 232.04, group: "actinide", grid: { row: 9, col: 5 } },
    { name: "Protactinium", symbol: "Pa", atomicNumber: 91, molarMass: 231.04, group: "actinide", grid: { row: 9, col: 6 } },
    { name: "Uranium", symbol: "U", atomicNumber: 92, molarMass: 238.03, group: "actinide", grid: { row: 9, col: 7 } },
    { name: "Neptunium", symbol: "Np", atomicNumber: 93, molarMass: 237, group: "actinide", grid: { row: 9, col: 8 } },
    { name: "Plutonium", symbol: "Pu", atomicNumber: 94, molarMass: 244, group: "actinide", grid: { row: 9, col: 9 } },
    { name: "Americium", symbol: "Am", atomicNumber: 95, molarMass: 243, group: "actinide", grid: { row: 9, col: 10 } },
    { name: "Curium", symbol: "Cm", atomicNumber: 96, molarMass: 247, group: "actinide", grid: { row: 9, col: 11 } },
    { name: "Berkelium", symbol: "Bk", atomicNumber: 97, molarMass: 247, group: "actinide", grid: { row: 9, col: 12 } },
    { name: "Californium", symbol: "Cf", atomicNumber: 98, molarMass: 251, group: "actinide", grid: { row: 9, col: 13 } },
    { name: "Einsteinium", symbol: "Es", atomicNumber: 99, molarMass: 252, group: "actinide", grid: { row: 9, col: 14 } },
    { name: "Fermium", symbol: "Fm", atomicNumber: 100, molarMass: 257, group: "actinide", grid: { row: 9, col: 15 } },
    { name: "Mendelevium", symbol: "Md", atomicNumber: 101, molarMass: 258, group: "actinide", grid: { row: 9, col: 16 } },
    { name: "Nobelium", symbol: "No", atomicNumber: 102, molarMass: 259, group: "actinide", grid: { row: 9, col: 17 } },
    { name: "Lawrencium", symbol: "Lr", atomicNumber: 103, molarMass: 262, group: "actinide", grid: { row: 9, col: 18 } }
];